#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal
function a() {
    rm /var/run/holbertonscript.pid
    exit
}
trap "echo I hate the kill command;a" SIGTERM
trap "echo Y U no love me?!;a" SIGINT
echo $$ >> /var/run/holbertonscript.pid
while [ true ]; do
    echo To infinity and beyond;
done
