#!/usr/bin/env bash
#this script displays to infinity and beyond indefinately with sleep 2 in between each iteration
trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
